// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpmgougmuyvgyumjcepf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwbWdvdWdtdXl2Z3l1bWpjZXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MzE5NjQsImV4cCI6MjA2MzEwNzk2NH0.7_j5gYGWKDVb4K5MGcw5d7doQGPymYwiwfTG09DrnAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);